### ISSUE TITLE
 使用CSS实现栅格布局

### ISSUE THREAD

**Issue by tailorr** [tailorr/blog#3]
# 使用CSS实现栅格布局
栅格系统暴露给开发者的概念只有行(Row)和列(Column)，但其内部实现还是CSS布局的应用，实现一响应式的栅格布局我们可以使用css grid, Flextbox, 或者float，目前而言，为了浏览器兼容，我们选择使用float布局来实现栅格系统
一个栅格系统主要包含四部分 1. Container(容器) 2.Row(行) 3. Column(列) 4. Gutter(列间距)
![](http://ww1.sinaimg.cn/large/d40e9753gy1fij38z5zpyj24m71dsdth.jpg)

### 首先，我们来定义Container

```css
/* 容器样式设置 */  
.container, 
.container-fluid {
  padding-left: 15px;/* 设置padding是为了后面Column直接嵌套Row预留 */
  padding-right: 15px;
  margin-left: auto;
  margin-right: auto;
}

.container *,
.container-fluid * {
    box-sizing: border-box;  
}
```

### 然后，我们来定义Row

```css
.row {
  margin-left: -15px;
  margin-right: -15px;  /* Container设置了padding，所以Row需要设置-margin让Row占满Container的宽度 */
}

.row:after { /* float会引起父元素的高度塌陷，所以要使用一些clearfix技巧来清除浮动 */
  content: "";
  display: table;
  clear: both;
}       
```

### 接下来，我们来定义Column，同时要考虑Gutter的设置

```css
 [class*='col-'] {
   float: left;
   min-height: 1px; 
   padding: 15px;  /* Gutter的设置 同时和前面Container设置的一样，所以Column里面可以直接嵌套Row，而不需要Container */
   border: 1px solid #F6A1A1;
   background-color: #FFDCDC;
}
```
这里，我们定义每个单元列为Container的1/12，SASS代码如下：

```scss
@for $i from 1 through 12 {
  .col-#{$i} {
    width: $i/12 * 100%;
  }
}
```
编译后的css 
```css
.col-1 {
    width: 8.33333%;
}

.col-2 {
    width: 16.66667%;
}

.col-3 {
    width: 25%;
}

.col-4 {
    width: 33.33333%;
}

.col-5 {
    width: 41.66667%;
}

.col-6 {
    width: 50%;
}

.col-7 {
    width: 58.33333%;
}

.col-8 {
    width: 66.66667%;
}

.col-9 {
    width: 75%;
}

.col-10 {
    width: 83.33333%;
}

.col-11 {
    width: 91.66667%;
}

.col-12 {
    width: 100%;
}
```
到这里，我们就实现了一个简单的12列栅格系统

[demo---栅格系统](http://tailorr.top/grid-system/grid.html)

### 响应式

然后我们来通过media query实现带响应式的栅格系统

```css
/* 小屏幕 平板等 屏幕宽度大于等于768px */
@media (min-width: 768px) {
  .col-sm-1 {
    width: 8.33333%;
  }
  .col-sm-2 {
    width: 16.66667%;
  }
  .col-sm-3 {
    width: 25%;
  }
  .col-sm-4 {
    width: 33.33333%;
  }
  .col-sm-5 {
    width: 41.66667%;
  }
  .col-sm-6 {
    width: 50%;
  }
  .col-sm-7 {
    width: 58.33333%;
  }
  .col-sm-8 {
    width: 66.66667%;
  }
  .col-sm-9 {
    width: 75%;
  }
  .col-sm-10 {
    width: 83.33333%;
  }
  .col-sm-11 {
    width: 91.66667%;
  }
  .col-sm-12 {
    width: 100%;
  }
}
/* 中等屏幕 桌面显示器等 屏幕宽度大于等于992px */

@media (min-width: 992px) {
  .col-md-1 {
    width: 8.33333%;
  }
  .col-md-2 {
    width: 16.66667%;
  }
  .col-md-3 {
    width: 25%;
  }
  .col-md-4 {
    width: 33.33333%;
  }
  .col-md-5 {
    width: 41.66667%;
  }
  .col-md-6 {
    width: 50%;
  }
  .col-md-7 {
    width: 58.33333%;
  }
  .col-md-8 {
    width: 66.66667%;
  }
  .col-md-9 {
    width: 75%;
  }
  .col-md-10 {
    width: 83.33333%;
  }
  .col-md-11 {
    width: 91.66667%;
  }
  .col-md-12 {
    width: 100%;
  }
}
/* 大屏幕 大桌面显示器等 屏幕宽度大于等于1200px */

@media (min-width: 1200px) {
  .col-lg-1 {
    width: 8.33333%;
  }
  .col-lg-2 {
    width: 16.66667%;
  }
  .col-lg-3 {
    width: 25%;
  }
  .col-lg-4 {
    width: 33.33333%;
  }
  .col-lg-5 {
    width: 41.66667%;
  }
  .col-lg-6 {
    width: 50%;
  }
  .col-lg-7 {
    width: 58.33333%;
  }
  .col-lg-8 {
    width: 66.66667%;
  }
  .col-lg-9 {
    width: 75%;
  }
  .col-lg-10 {
    width: 83.33333%;
  }
  .col-lg-11 {
    width: 91.66667%;
  }
  .col-lg-12 {
    width: 100%;
  }
}
```

[demo---带响应式的栅格系统](http://tailorr.top/grid-system/grid-responsive.html)
